const images = {
 
       Home: require('../../assets/Home.png'),
       Accounting: require('../../assets/Accounting.png'),
       Recruitment: require('../../assets/Recruitment.png'),
       Assets: require('../../assets/Assets.png'),
       Build: require('../../assets/Build.png'),
       Buying: require('../../assets/Buying.png'),
       EmployeeLifecycle: require('../../assets/EmployeeLifecycle.png'),
       CRM: require('../../assets/CRM.png'),
       ShiftAttendance: require('../../assets/ShiftAttendance.png'),
       HR: require('../../assets/HR.png'),
       Customization: require('../../assets/Customization.png'),
       ExpenseClaims: require('../../assets/ExpenseClaims.png'),
       SalaryPayout: require('../../assets/SalaryPayout.png'),
       ERPNextIntegrations: require('../../assets/ERPNextIntegrations.png'),
       Leaves: require('../../assets/Leaves.png'),
       ERPNextSettings: require('../../assets/ERPNextSettings.png'),
       Performance: require('../../assets/Performance.png'),
       Payroll: require('../../assets/Payroll.png'),
       Integrations: require('../../assets/Integrations.png'),
       Loans: require('../../assets/Loans.png'),
       Manufacturing: require('../../assets/Manufacturing.png'),
       Projects: require('../../assets/Projects.png'),
       Quality: require('../../assets/Quality.png'),
       Retail: require('../../assets/Retail.png'),
       Selling: require('../../assets/Selling.png'),
       Stock: require('../../assets/Stock.png'),
       Support: require('../../assets/Support.png'),
       Tools: require('../../assets/Tools.png'),
       Users: require('../../assets/Users.png'),
       Website: require('../../assets/Website.png'),
       Settings: require('../../assets/Settings.png'),
       Utilities: require('../../assets/Utilities.png'),
       TaxBenefits: require('../../assets/TaxBenefits.png'),
    
    };
    
    export default images;